apiVersion: v1
kind: Secret
metadata:
  name: patient-management-secrets
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: "admin_user"
  POSTGRES_PASSWORD: "password"
  PATIENT_POSTGRES_DB: "patient_db"
  AUTH_POSTGRES_DB: "auth_db"
  JWT_SECRET: "bXktc3VwZXItc2VjdXJlLWF1dGgtc2VydmljZS1qd3Qtc2VjcmV0LTEyMzQ1Ng=="
