apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-management-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"

  PATIENT_SERVICE_PORT: "4000"
  BILLING_SERVICE_PORT: "4001"
  BILLING_GRPC_PORT: "9001"
  ANALYTICS_SERVICE_PORT: "4003"
  AUTH_SERVICE_PORT: "4004"
  API_GATEWAY_PORT: "4005"

  PATIENT_SERVICE_URL: "http://patient-service:4000"
  AUTH_SERVICE_URL: "http://auth-service:4004"
  BILLING_SERVICE_ADDRESS: "billing-service"
  BILLING_SERVICE_GRPC_PORT: "9001"

  PATIENT_DATASOURCE_URL: "jdbc:postgresql://patient-service-db:5432/patient_db"
  AUTH_DATASOURCE_URL: "jdbc:postgresql://auth-service-db:5432/auth_db"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  PATIENT_SQL_INIT_MODE: "always"
  AUTH_SQL_INIT_MODE: "never"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_TOPIC_PATIENT: "patient"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "org.apache.kafka.common.serialization.ByteArraySerializer"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.apache.kafka.common.serialization.ByteArrayDeserializer"

  JWT_EXPIRATION_MS: "180000"
  JWT_ISSUER: "auth-service"
  JWT_AUDIENCE: "patient-management"
