apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: patient-management-k8s
  labels:
    app: kafdrop
spec:
  type: NodePort
  selector:
    app: kafdrop
  ports:
    - name: http
      port: 9091
      targetPort: 9091
      nodePort: 30091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: patient-management-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9091
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka:9092"
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
            - name: SERVER_PORT
              value: "9091"
          readinessProbe:
            tcpSocket:
              port: 9091
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9091
            initialDelaySeconds: 40
            periodSeconds: 20
