apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: default
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: analytics-service
          image: ghcr.io/patient-management-microservices/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4003
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: patient-management-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: patient-management-config
                  key: ANALYTICS_SERVICE_PORT
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: patient-management-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
              valueFrom:
                configMapKeyRef:
                  name: patient-management-config
                  key: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
            - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
              valueFrom:
                configMapKeyRef:
                  name: patient-management-config
                  key: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx384m"
          readinessProbe:
            tcpSocket:
              port: 4003
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 18
          livenessProbe:
            tcpSocket:
              port: 4003
            initialDelaySeconds: 150
            periodSeconds: 20
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
